### ISSUE TITLE
Q: Best Practices for ENV vars

### ISSUE THREAD

**Issue by composer22** [signalfx/docker-collectd#10]
Can you please give some advice on optimizing the following? Unclear how we should allocate
- COLLECTD_BUFFERSIZE

Also, is 10 seconds overkill or can you make a suggestion on what would make sense and the implications of lowering this? What are most of your customers normally setting this to?
- COLLECTD_FLUSHINTERVAL
- COLLECTD_INTERVAL

**Comment by mdubbyap** [comment]
The defaults provided should work in most environments.  We've have customers running FlushInterval set to 2 without any issues and i've tested 1.  If there are no metrics, it's a noop.

As for BufferSize, i would only increase this if you're producing a lot of metrics. You can monitor by looking at the queue_length metric from the plugin 'collectd'.  If this is growing over time, you're getting behind and should probably increase the BufferSize.  If this is the case i would double it and see what happens.

matthew.
