### ISSUE TITLE
Unable to run image

### ISSUE THREAD

**Issue by abhijeetpathak** [signalfx/docker-collectd#40]
I get following while creating a new container:

`docker: Error response from daemon: linux runtime spec devices: lstat /dev/.bootchart/proc/4261/fdinfo/12: no such file or directory.`

I tried both Ubuntu and Alpine based images.

**Comment by abhijeetpathak** [comment]
My machine: Ubuntu 15.10 64bit

**Comment by codesmith14** [comment]
Hi @abhijeetpathak ,

Thank you for reporting this issue.  I am looking into it.

Can you please provide me with the following additional information:

- Are you attempting to build our image using the docker files in this repository?
    - Or are you using our hosted images?
    - Or are you extending the hosted images in a new dockerfile?
- Can you please provide the terminal command and options you are using to run/start the container?  (Please anonymize any authentication tokens)
- If you are adding additional plugins or configurations to the container beyond what are built in please list them, and if possible provide the anonymized versions of the configuration files.

-- Charlie

**Comment by abhijeetpathak** [comment]
Pulled the images from docker hub. Haven't built them myself.

`sudo docker run --privileged   --net="host"   -v /etc/hostname:/mnt/hostname:ro   -v /proc:/mnt/proc:ro   -v /etc:/mnt/etc:ro   quay.io/signalfuse/collectd:latest`

`sudo docker run --privileged   --net="host"   -v /etc/hostname:/mnt/hostname:ro   -v /proc:/mnt/proc:ro   -v /etc:/mnt/etc:ro   quay.io/signalfuse/collectd-alpine:latest`

**Comment by codesmith14** [comment]
Hi @abhijeetpathak,
I have successfully reproduced the issue you were seeing.  I tested on a fresh ubuntu 15.10 installation and was unable to reproduce it, but I noticed the file in the error was from an application called "bootchart".  So, I installed bootchart on my test environment and I am able to consistently reproduced the issue.  Unfortunately the issue appears to be between docker and bootchart.  Something is incompatible between bootchart and docker's `--privileged` option.

You can verify this by running a plain ubuntu container:
```bash
$sudo docker run --privileged ubuntu:16.04 /bin/echo "hello world"
docker: Error response from daemon: linux runtime spec devices: open /dev/.bootchart/proc/1844: no such file or directory.
```

If you remove the --privileged flag, the container runs as expected:
```bash
$ sudo docker run ubuntu:16.04 /bin/echo "hello world"
hello world
```

At the moment the `--privileged` docker feature is a requirement for our collectd container to report accurate metrics on the host.

**Comment by abhijeetpathak** [comment]
So isn't there any fix for this?

**Comment by codesmith14** [comment]
I am unaware of any fixes from docker or bootchart.  Unfortunately the bug exists between docker and bootchart, so a fix will have to come from one of those projects.  I would recommend raising an issue with one or both development communities.
