### ISSUE TITLE
Dependency jq Not Installed

### ISSUE THREAD

**Issue by keitwb** [signalfx/docker-collectd#46]
This will probably be an issue if this is deployed to AWS: the CLI tool `jq` is not installed in the Dockerfile and thus [the logic to determine the AWS_UNIQUE_ID](https://github.com/signalfx/docker-collectd/blob/master/ubuntu/run.sh#L197) won't work.

**Comment by codesmith14** [comment]
We can install that if it's necessary for the unique id to be appended to all metrics.  The metdata plugin should be able to propagate the unique id as a host property.  If that's sufficient, then we can just remove that statement form the run script.

**Comment by cep21** [comment]
We have also ran into this issue.

**Comment by keitwb** [comment]
https://github.com/signalfx/docker-collectd/pull/55 should fix it once merged and deployed.

**Comment by keitwb** [comment]
JQ is now available in the `latest` tag of both the Ubuntu and Alpine images.
