### ISSUE TITLE
Do I need writable docker cross mount?

### ISSUE THREAD

**Issue by cep21** [signalfx/docker-collectd#53]
Hi,

The readme has  `-v /var/run/docker.sock:/var/run/docker.sock`

Will the image work well with `  -v /var/run/docker.sock:/var/run/docker.sock:ro` (in other worse, making the docker socket read only in the container.

Thanks!

**Comment by codesmith14** [comment]
Hi @cep21,
Our docker collectd plugin requires read and write access to the docker socket in order to make requests for information from it.  If you are not interested in docker metrics, you may leave off the mount point entirely.

**Comment by cep21** [comment]
Can you clarify what write operations the plugin needs to do to the docker socket?  It doesn't make sense that a metrics reporting plugin would need to write anything to the localhost.
