### ISSUE TITLE
Suggestions on improving support for ECS

### ISSUE THREAD

**Issue by cep21** [signalfx/docker-collectd#54]
Hi,

I made a private fork to support docker-collectd deployed on ECS.  It has too much private to submit a pull request, but I made the following changes to support ECS.

1. Install jq on the docker container to support run.sh
2. Set the `host` to the AWS instance running the collectd agent.  I had to do this to give each ECS container host a unique `host` name to make the UI's Infrastructure -> Hosts assumption that `host` is something to aggregate one valid.

The diff is something like this

```
diff --git a/alpine/Dockerfile b/alpine/Dockerfile
index c886d2c..96426c6 100644
--- a/alpine/Dockerfile
+++ b/alpine/Dockerfile
@@ -46,6 +46,7 @@ RUN apk update \
     && apk add collectd \
                collectd-python \
                collectd-write_http \
+               jq \
                signalfx-collectd-plugin \
     # Clean up existing configs
     && rm -rf /etc/collectd \
diff --git a/alpine/run.sh b/alpine/run.sh
index 5890a4f..9577bff 100755
--- a/alpine/run.sh
+++ b/alpine/run.sh
@@ -66,6 +66,11 @@ fi
 #If the user sets COLLECTD_HOSTNAME then assign to HOSTNAME
 if [ -n "$COLLECTD_HOSTNAME" ]; then
        HOSTNAME="Hostname \"$COLLECTD_HOSTNAME\""
+elif [ -n "$COLLECTD_HOSTNAME_INSTANCE_ID" ]; then
+       # When ran inside an ECS cluster, each run of the task needs a new
+       # HOSTNAME.  Since you can't define one in the task definition, use metadata
+       # to get one.
+       HOSTNAME="Hostname \"$(curl http://169.254.169.254/latest/meta-data/instance-id)\""
 #If the host's hostname is mounted @ /mnt/etc/hostname, then assign to HOSTNAME
 elif [ -e /mnt/hostname ]; then
     HOST_HOSTNAME=$(cat /mnt/hostname)
```

**Comment by keitwb** [comment]
Do you know if mounting the `/etc/hostname` file from the rootfs of the underlying EC2 instance to `/hostfs/etc/hostname` and letting the logic at https://github.com/signalfx/docker-collectd/blob/master/alpine/run.sh#L75 pick that up would work?  Just want to avoid making these run scripts any more complicated than they are, esp. since we are maintaining two of them (which could probably be merged into one or at least share a lot of stuff).

**Comment by cep21** [comment]
I'm using the AWS ecs optimized AMI.  I don't see a file at /etc/hostname.  The syscontrol file is this
```
[jlindamo@ip-10-198-26-194 etc]$ cat /etc/sysconfig/network
NETWORKING=yes
HOSTNAME=localhost.localdomain
NOZEROCONF=yes
```

Is there another place I should look?

**Comment by keitwb** [comment]
Nope, I think your technique is about as good as any.  Their distro apparently just doesn't set `/etc/hostname` and I can't see any clearer way of getting it.  Thanks for the suggestion, we'll incorporate it when we get a chance.

**Comment by jsm** [comment]
Would greatly appreciate this as well
