### ISSUE TITLE
StatsD

### ISSUE THREAD

**Issue by jsm** [signalfx/docker-collectd#58]
Does this also run a statsd forwarder? It says on https://github.com/signalfx/integrations/tree/master/collectd-statsd

> This plugin is included by default with all versions of the SignalFx collectd agent.

But, sending stuff to 8125 doesn't seem to show anything on my dashboards?

- Which image are you using?:
    - quay.io/signalfuse/collectd (Ubuntu)
- How are you getting the image?
    - [] Pulling and running the hosted images
- Are you using the latest version of the image?
    - [x] yes
    - [] no
files, or directories)
        - []
- Please provide any output from the container or container log

**Comment by jsm** [comment]
Actually I see this in the logs:

`dogstatsd: dogstatsd port listening not enabled` Is there a flag I'm missing to enable it?

**Comment by codesmith14** [comment]
@jsm  This configuration was not easily accessible.  PR#59 should address this by reading the environment variable DOG_STATSD_PORT in the container on startup.  In addition to setting that environment variable on the container, you'll need to expose the port on the container using the `docker run` `-p` option.  Thank you for reaching out.

**Comment by jsm** [comment]
@charliesignalfx Thanks a bunch for the patch! Was using hitting it through the internal docker network, so the exposed port wasn't the issue. Please let me know when I can use the quay repo with this.

**Comment by codesmith14** [comment]
@jsm  No problem.  The images are up now.  If you pull the latest image you should get the changes.
